# Update the URL: change 'mysql' to 'postgresql' and the port to 5432
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb

spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Settings
jwt.secret-key=${JWT_SECRET_KEY:default-256-bit-secret-key-for-dev-only-change-in-prod}